server {
    listen 80;
    server_name localhost;
    root /var/www/public;
    index index.php index.html;

     # WebSocket → Reverb container
    # location /app/ {
    #     proxy_pass http://reverb:8080;
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";
    #     proxy_set_header Host $host;
    #     proxy_read_timeout 60s;
    #     proxy_send_timeout 60s;
    #     proxy_buffering off;
    # }

    location / {
        try_files $uri $uri/ /index.php$is_args$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht{
        deny all;
    }
}
